// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS6EpgtGO5GPtbW9T-pAB3ZxqyZzw0tpI',
    appId: '1:5599318030:web:7dc4ed8ca497c64f046c5f',
    messagingSenderId: '5599318030',
    projectId: 'framewor-e-commerce',
    authDomain: 'framewor-e-commerce.firebaseapp.com',
    storageBucket: 'framewor-e-commerce.appspot.com',
    measurementId: 'G-GYR6YYX9C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU3up1VQgCA0y5pWEV8vYmxCZY8OKNOUU',
    appId: '1:5599318030:android:ca62b9c5443ba630046c5f',
    messagingSenderId: '5599318030',
    projectId: 'framewor-e-commerce',
    storageBucket: 'framewor-e-commerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmLYEw3W_CvWBDDI-XkoaFUHLHbUNrZV4',
    appId: '1:5599318030:ios:32fd23c3098f12e8046c5f',
    messagingSenderId: '5599318030',
    projectId: 'framewor-e-commerce',
    storageBucket: 'framewor-e-commerce.appspot.com',
    iosClientId: '5599318030-fdaqkikn2s6krbq2o968fg0ric0v3jpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.frameworkECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmLYEw3W_CvWBDDI-XkoaFUHLHbUNrZV4',
    appId: '1:5599318030:ios:2c5818089981e524046c5f',
    messagingSenderId: '5599318030',
    projectId: 'framewor-e-commerce',
    storageBucket: 'framewor-e-commerce.appspot.com',
    iosClientId: '5599318030-32rrebfh95qrn020meb16olgs1rm3e72.apps.googleusercontent.com',
    iosBundleId: 'com.example.frameworkECommerce.RunnerTests',
  );
}
